version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "generator"
    cmds:
      - go run .\cmd\migrator\main.go -storage-path "postgres:postgres@localhost:5432/order_service?sslmode=disable" -migrations-path migrations
      - mockgen -source=internal/services/order.go -destination=internal/repository/mocks/mock_repository_create_order.go