version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Migrations generator"
    cmds:
      - go run .\cmd\migrator\main.go -storage-path "postgres:postgres@localhost:5432/order_service?sslmode=disable" -migrations-path migrations