# config/config.yaml

env: "local"
http:
  port: 8080
postgres:
  port: 5432
  host: "postgres"
  db_name: "order_service"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
kafka:
  order_event_topic: "order_topic"
  status_event_topic: "status_topic"
  broker_list:
    - "localhost:9092"
  port: "9092"